### PR TITLE
optimizing_implicit_code  [WIP]

### PR DESCRIPTION
**Pull request by srobertp**
add two test functions and start to vectorize other functions.  added some comments and rewrote to be more clear.

Still more to do, but it is already starting to be faster.

### CODE REVIEW

**Comment by srobertp** [comment]
@lwy5515 With this latest push, the code is significantly faster since many of the functions have been vectorized and we are taking advantage of the speed of builtin functions and vector matrix operations instead of for loops.  

Do you want to look through it and see if it is still readable?  I tried to keep everything clean and easy to follow as well as changing up the documentation to be consistent with the new forms.

I was thinking we should have them create the another error norm that doest the L2(Gamma_h) and H1(D_h) norms  which is the norm that the theorems give proofs for.

Anything else we want to do in the implicit code before they get it?

If you like it, then go ahead and merge this into master. otherwise we can keep working on the optimization and try to make it easier to read.

**Comment by lwy5515** [comment]
I am okey with your modification.
Should we visualize the numerical solution?

**Comment by srobertp** [comment]
@lwy5515 That is a great idea to visualize the solution.  I am thinking it might be good to have both the solution and the error visualized on Gamma_h.  I can write that up.  It shouldn't be too hard.  While I am doing it, I will move the error analysis to it's own file called compute_error_L2_Gamma_h() which will get them set up to make other types of error functions and call them from the script.

**Comment by srobertp** [comment]
@lwy5515 Okay, the plotting is added and hte error is moved to it's own file.  If you look through it and think it is enough, then go ahead and merge this pull request to master.  I think it is looking pretty good.

**Comment by lwy5515** [comment]
Does matlab create a copy in the memory when pass down nb_node, nb_ele to a function?

**Comment by srobertp** [comment]
@lwy5515  Check out this answer for all the details.  The short answer is, not if we don't change the data inside the function. They call it lazy passing.

http://blogs.mathworks.com/loren/2006/05/10/memory-management-for-functions-and-variables/

Kind of a clever data management. It's too bad there isn't a keyword we could pass in to tell them it is static... I guess it figures it out

**Comment by lwy5515** [comment]
Great news! So we can now merge this into the master.

**Pull request merged**
