### PR TITLE
vertorize the code for parametric case

### PR DESCRIPTION
**Pull request by lwy5515**
So I vectorize the code for parametric case. It seems that I cannot update date the node and connectivity list for the parametric domain. At least I cannot change the node list because I cannot visit the cells on the periodic boundary. To get surface nodes, we can somehow extract from the parametric node list (see line 86-88 in the main script). What do you think?

### CODE REVIEW

**Comment by srobertp** [comment]
@lwy5515 Try the following code to do the relabeling.  It should give you n^2 points and the connectivity list using those n^2 nodes:

<pre>
clear all; clc; close all;
n = 4;
% Triangulation on the square [-\pi,\pi]*[-\pi,\pi].
h=2*pi/n;
xx=-pi:h:pi;
yy=-pi:h:pi;
[YY,XX]=meshgrid(yy,xx);
%
% Create basic triangulation before imposing periodicity constraints
%
X=zeros((n+1)*(n+1),2);
X(:,1)=reshape(XX,(n+1)^2,1);
X(:,2)=reshape(YY,(n+1)^2,1);
dt = delaunayTriangulation(X);
%
% Identify the periodic nodes and create mapping to adjust the nodes
%
mapping_to_periodic = (1:(n+1)^2)';
mapping_to_periodic = reshape(mapping_to_periodic,n+1,n+1);
% fix x direction
mapping_to_periodic(:,end) = mapping_to_periodic(:,1);
% fix y direction
mapping_to_periodic(end,:) = mapping_to_periodic(1,:);
mapping_to_periodic = reshape(mapping_to_periodic,(n+1)^2,1);
%
% Relabel to get continuous labels 1:n^2.
%
unique_nodes = unique(mapping_to_periodic);
inverse_unique_nodes = zeros(max(unique_nodes),1);
inverse_unique_nodes(unique_nodes) = 1:n^2;
mapping_to_periodic = inverse_unique_nodes(mapping_to_periodic);
%
% Change connectivity list to enforce the periodic constraints and new labeling.
% We end up with a periodic triangulation on n^2 nodes.
%
elem = mapping_to_periodic(dt.ConnectivityList);
node = dt.Points(unique_nodes,:);
%
% Plot and compare triangulations
%
% original triangulation
subplot(211),triplot(dt); axis([-4 4 -4 4]);
% periodic triangulation
subplot(212), triplot(elem,node(:,1),node(:,2)); axis([-4 4 -4 4]);
</pre>

**Comment by lwy5515** [comment]
So it produce the mesh in the second figure. But this is not what we want to compute on. That affine mapping is changed.

**Comment by lwy5515** [comment]
@srobertp So it produce the mesh in the second figure. But this is not what we want to compute on. The affine mapping is changed.

**Comment by srobertp** [comment]
@lwy5515 I am not sure I understand then.  This mesh has the periodicity built in so that the four corners of the original mesh are the same point, and the left side is the right side and top side is the bottom side.  

The affine mapping should be the same through the chi mapping.  While the parameter space does not appear to be periodic, parameterization(parameter space) is.  See the following.

<pre>
clear all; clc; close all;
n = 5;
% Triangulation on the square [-\pi,\pi]*[-\pi,\pi].
h=2*pi/n;
xx=-pi:h:pi;
yy=-pi:h:pi;
[YY,XX]=meshgrid(yy,xx);
%
% Create basic triangulation before imposing periodicity constraints
%
X=zeros((n+1)*(n+1),2);
X(:,1)=reshape(XX,(n+1)^2,1);
X(:,2)=reshape(YY,(n+1)^2,1);
dt = delaunayTriangulation(X);
[n_n,~] = size(dt.Points);
[n_e,~] = size(dt.ConnectivityList);
%
% identify the periodic nodes and create mapping to adjust the nodes
%
mapping_to_periodic = (1:(n+1)^2)';
mapping_to_periodic = reshape(mapping_to_periodic,n+1,n+1);
% fix x direction
mapping_to_periodic(:,end) = mapping_to_periodic(:,1);
% fix y direction
mapping_to_periodic(end,:) = mapping_to_periodic(1,:);
mapping_to_periodic = reshape(mapping_to_periodic,(n+1)^2,1);
% relabel to get continuous labels 1:n^2.
unique_nodes = unique(mapping_to_periodic);
inverse_unique_nodes = zeros(max(unique_nodes),1);
inverse_unique_nodes(unique_nodes) = 1:n^2;
mapping_to_periodic = inverse_unique_nodes(mapping_to_periodic);
% change connectivity list to enforce the periodic constraints and new
% labeling
elem = mapping_to_periodic(dt.ConnectivityList);
node = dt.Points(unique_nodes,:);
[n_nodes,~] = size(node);
[n_elem,~] = size(elem);
% original triangulation
subplot(221),triplot(dt); axis([-4 4 -4 4]);
% adjusted triangulation
subplot(222), triplot(elem,node(:,1),node(:,2)); axis([-4 4 -4 4]);
% original triangulation
XOriginal = chi(dt.Points);
subplot(223), axis([-2 2 -2 2 -2 2]);
for i=1:n_e
    XX=XOriginal(dt.ConnectivityList(i,:),1);
    YY=XOriginal(dt.ConnectivityList(i,:),2);
    ZZ=XOriginal(dt.ConnectivityList(i,:),3);
    CC=zeros(3,1);
    patch(XX,YY,ZZ,CC);
end
% adjusted triangulation
Xperiodic = chi(node);
subplot(224), axis([-2 2 -2 2 -2 2]);
for i=1:n_elem
    XX=Xperiodic(elem(i,:),1);
    YY=Xperiodic(elem(i,:),2);
    ZZ=Xperiodic(elem(i,:),3);
    CC=zeros(3,1);
    patch(XX,YY,ZZ,CC);
end
</pre>

with chi.m vectorized:

<pre>
function [ x ] = chi( y )
% Parameterization 
%  chi(y) = x \]in R^3 on torus
%
R=1; r=0.6;
[n,~] = size(y);
x=zeros(n,3);
x(:,1)=(R+r*cos(y(:,1))).*cos(y(:,2));
x(:,2)=(R+r*cos(y(:,1))).*sin(y(:,2));
x(:,3)=r*sin(y(:,1));
end
</pre>

**Comment by srobertp** [comment]
Am I missing something?

**Comment by lwy5515** [comment]
@srobertp The problem is what we compute stays on the parametric domain except assembling.
Assume we compute the local stiffness matrix in a cell. We actually get three nodes in the parametric domain and compute the affine matrix using coordinates of these nodes, that is 

mat_B = [v(2,:)-v(1,:); v(3,:)-v(1,:)]' ;

If we use the extracted node list, mat_B is changed when cell is on the boundary of the parametric domain. Another way to think is that |det(mat_B)| (area of the cell) should be a constant since this is uniform mesh. But base on the mesh printed out (second figure), we do not have this property.

**Comment by srobertp** [comment]
@lwy5515 Oh, I think I understand what you are saying.  The affine mapping from the parameter space mapping to the reference triangle would need to be different.

That is too bad, because this gives the parameter domain with the minimal number of nodes required.  I suppose that what we are doing is the way to do it for using a reference triangle.  And I guess we don't want to change to higher order elements elsewhere.

I am thinking about dealii approaches.  They have the constraint matrix setup with the periodic constraints. So they essentially reduce the system and remove duplicate nodes before they solve after assembly.

**Comment by srobertp** [comment]
@lwy5515 so essentially we could do the assembly as usual without a global index (Then the contributions for duplicate nodes are scattered into different rows of the matrix) and then write a function that applies the periodic conditions and condenses the system to unique nodes before we solve...

I imagine we could use some of the code written above to do so.

Or we could leave it as is with a global index mapping which points all the duplicates to one node and construct the matrix system .  Then we extract the submatrix of unique nodes and solve it...

**Comment by srobertp** [comment]
@lwy5515 I think it is just fine the way it is.  I like the simplicity of mapping indices to global_indices which goes from 1:n^2.  So we really only construct the submatrix.  The part at the end where you are extracting the unique nodes looks good too.  Maybe add a comment describing what you are doing there, ie extracting unique nodes that correspond to the submatrix set of global_indices...

**Comment by lwy5515** [comment]
@srobertp What I did is to return the number of vertices on the surface (n_ndoe = n*n) and the node list on the parametric domain ((n+1)^2 by 2 matrix , but I did not return the length of this list). I consider the global_ind mapping as a constraint matrix. After that the size of matrix you construct is exactly the size on the surface. Is that okey?

For a general case, to extract the surface nodes in the parametric node list, we may generate the inverse  of the global_ind when we generating the mesh.

**Comment by lwy5515** [comment]
@srobertp So I vectorized the global_ind and add global_ind_inverse to extract unique nodes from the parametric node list. How about now?

It is a little tricky when considering unstructured mesh.

**Comment by srobertp** [comment]
@lwy5515 did you commit the new triangulation_surface.m  function?

**Comment by srobertp** [comment]
@lwy5515 , I agree for the unstructured mesh, we need to enforce that the boundary nodes are structured in some manner so that we have them line up properly.  I think it is possible if we give them as a list of nodes to use...  I am not sure I see a clear way to do that and enforce that they are not subdivided...

**Comment by lwy5515** [comment]
@srobertp I add some comments about different indexing between surface and parametric domain. How does it look right now?

**Pull request merged**
