### PR TITLE
wl/add_implicit_ls_fe code

### PR DESCRIPTION
**Pull request by srobertp**

### CODE REVIEW

**Comment by srobertp** [comment]
@lwy5515 I went ahead and merged my subdivide branch into master and have created this new pull request for your code.  It shouldn't have any issues with merging with the stuff I have put in so whenever you are ready, go ahead and merge it.  At that point we can start dividing up the remaining work that needs to be done:
- [ ] Add README.txt with description of how to run the files and what parameters can be adjusted
- [ ] Add commentary and descriptions to files
- [ ] Decide on what types of tasks we will give the attendees to do in lab
- [ ] Run the tests ourselves to ensure we are getting proper convergence orders.
- [ ] anything else?

**Comment by lwy5515** [comment]
@srobertp Maybe I should explain what I did in my code. I actually wrote the initialing, assembling, solving and error computing routines in a single file level_set_torus.m. I firstly used meshabox function to generate the narrow band mesh and then report the L2 error with different h. So I have the following table.

h          l2 error          rate
0.2       0.844            --
0.1       0.280            1.59
0.05     0.07965        1.81
0.025   0.02382        1.74

I cannot compute the case for h=0.0125 because tetgen cannot generate such a big mesh. We explain somehow the rate because h is the mesh size for the big box instead of the narrow band mesh. To get a better results, I try to matlab function to generate a uniform mesh for the narrow band (the function 'uniform_bulk_mesh.m') and n is the number of intervals on each direction. L2 error looks like the following

n        l2 error         rate
16      0.7602          --
32      0.2619          1.537
64      0.075361      1.797
128    0.01967        1.938

It looks reasonable since we can see somehow the second order convergence rate in table. 

I will continue to add commentary and descriptions for the first case (parametric case). About tasks for attendees, maybe we can present a different surface and a different level set function (may not be the signed distant function) for them to compute.

Another thing is to decide the schedule for our lab session and start to write down our lab notes. Should we write the notes down as tex file or just my hand?

**Comment by srobertp** [comment]
@lwy5515 Let's write them in tex file, so it is easier to pass back and forth.  What kind of notes do you think we need to prepare?  I guess we need to decide on what we are assuming they already know and then work from there.

Have you ever used Slack before?  It might be a better place for us to communicate the simple things back and forth and it integrates with git so that as things pop up or change, they can be seen there.  It is a little easier to communicate and if we need to coordinate things it is pretty easy to chat there.   I sent you an invite.

**Comment by srobertp** [comment]
@lwy5515 I don't know if we need it or not but I set up the slack team for our geometric pde winter school.  It was free and easy.  I also integrated the github account into it.  If we end up not using it, no problem.

**Pull request merged**
