### PR TITLE
Srp/rename folders housekeeping

### PR DESCRIPTION
**Pull request by srobertp**

### CODE REVIEW

**Comment by srobertp** [comment]
@lwy5515 Here is the src/ folder with the general codes as we discussed earlier today.  Are there any other functions which you would like moved to the src/ folder?  It will be necessary to add src/ to our search paths, but I think this is the right way to do it.  And, we may end up just giving everyone the src/ folder for their own codes.  We can add another couple of folders to master, mainly something like the 

2DFEM_linear/
3DFEM_linear/

with README.txt that explain the specific problem being solved, mainly

-\Delta u + u = f in 2D or 3D
with homoegeneous neuman BC

with linear shape functions and assembly done on a reference triangle vs assembly done in real space.

what do you think?

**Comment by lwy5515** [comment]
I think I do not have any more move to /src right now.  For 2D and 3D general FE problem, how about assembling using reference triangle in 2D and assembling in real space in 3D?

**Comment by srobertp** [comment]
@lwy5515 I like that.  2D on reference triangle and 3D in real space.  I will add the README files and include those descriptions.

**Comment by lwy5515** [comment]
@srobertp Sorry I forgot to commit it.

**Pull request merged**
